name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to SSH server and update the project
      run: |
        sshpass -p Jood2023 ssh -o StrictHostKeyChecking=no -l root@85.214.222.77 "cd /var/www/vhosts/heiratsvertrag-ig-oldenburg.de/api.heiratsvertrag-ig-oldenburg.de/contracts-project && git pull origin main"