name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key to known hosts
      run: ssh-keyscan 85.214.222.77 >> ~/.ssh/known_hosts
        
    - name: Connect to SSH server and update the project
      run: |
        sshpass -p "Jood2023" ssh -tv root@85.214.222.77 "cd /var/www/vhosts/heiratsvertrag-ig-oldenburg.de/api.heiratsvertrag-ig-oldenburg.de/contracts-project && git pull https://hrr2000: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@github.com/olaju2001/contracts-project.git main"
        
        
        